name: 'Serverless Stack (SST) deploy'
description: 'This action deploys a serverless stack application to the staging environment of your choice'
inputs:
  access-key-id:
    description: 'AWS access key id'
    required: true
  secret-access-key:
    description: 'AWS secret access key'
    required: true
  region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  stage: 
    description: 'The stage name (default is production)'
    required: false
    default: production
  path:
    description: 'Path to the serverless stack'
    required: false
    default: '.'
  pkg-manager:
    description: 'Package mangers for your lock file. options are npm, yarn. (default yarn)'
    required: false
    default: 'yarn'
  envs:
    description: 'Environmental variables passed into SST using secrets'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'cloud'
  color: 'orange'
